---
swagger: '2.0'
info:
    title: Do API
    description: Please reach out on discord @do.
    version: 1.0.0
definitions: {}
paths:
    '/health':
        get:
            responses:
                '200':
                    description: Default Response
    '/conversations':
        get:
            responses:
                '200':
                    description: Default Response
                    schema:
                        type: array
                        conversations:
                            type: object
                            properties:
                                id:
                                    type: integer
                                value:
                                    type: string
        post:
            responses:
                '201':
                    description: Default Response
                    schema:
                        type: object
                        properties:
                            id:
                                type: integer
                            value:
                                type: string
    '/conversation{id}':
        get:
            parameters:
                - type: string
                  required: true
                  in: path
                  name: id
            responses:
                '200':
                    description: Default Response
                    schema:
                        type: object
                        properties:
                            id:
                                type: integer
                            value:
                                type: string
host: localhost
schemes:
    - http
    - https
consumes:
    - application/json
produces:
    - application/json
